### ISSUE TITLE
Snes9x 2010 core - Brunnis lag fix

### ISSUE THREAD

**Issue by baco81** [SuperrSonic/RA-SS#10]
Hello Superrsonic!

First of all, thank you for your amazing work :)

Could you merge this commit into your code, please?

https://github.com/libretro/snes9x2010/commit/0a6671f0c28f6fe19a96836168479c4b71d583df

It removes 1 frame of unnecessary input lag.

More info here:

https://github.com/libretro/snes9x2010/issues/74

Thank you again!

**Comment by SuperrSonic** [comment]
It's in. For reference every SNES core now has the lag fix, except Next which is included as a last resort in case it's needed for whatever reason. [This is the snapshot used.](https://github.com/libretro/snes9x2010/tree/8560ef4f6c767c4b00ab1b97516355c7c397038b)

**Comment by baco81** [comment]
Thank you!!
