### ISSUE TITLE
Exit to menu key combo

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#14]
Hello, on normal retroarch you can use left + right triggers + select + start to exit to menu but you've removed that for this version? I tried to assign it myself under menu toggle but it only allows one button to be assigned rather than simultaneous buttons. Please could you make it so I can use a key combo to exit to menu? (Using snes or GameCube controller)

**Comment by SuperrSonic** [comment]
It was removed before this became a public release, since I only use controllers that have an extra button or stick available, keeping the menu combo felt unnecessary.

It can be made into a setting.

**Comment by filevans** [comment]
Tremendous work anyway really good

**Comment by SuperrSonic** [comment]
It's finished, if it's set to 1 it will use the RA combo, if 2 it will use GC reset (X, B, Start) it will only work correctly if the input profile is set to 0 and only GC controllers are active.

For your other requests, I have no plans to add multiple mappings to one button, but your very specific requests can be done via the core, so suggest it on the core's repo. Some cores might already support it.

**Comment by filevans** [comment]
I can't get this to work. I don't know what you mean set to 1? Set which to 1? I have GC controller in and none of those exit shortcuts are working

**Comment by SuperrSonic** [comment]
Settings->Input->Menu Combo set to 1.

When you don't know what a particular setting does, you should press the info button (Z or Minus), most settings are covered.

**Comment by filevans** [comment]
Thanks, it would be better if menu button combo still worked with Wiimote in as if you forget to enable it (as default is disabled) then you have to put your Wiimote on to get back to the menu, then you have to exit the emulator and turn your Wiimote off for it to start being able to use the button combo on the GameCube/SNES controller. So it's very long winded to use it if you forget to enable it, as it's also a long way down the list in the input settings, would be better if was at the top somewhere too. Thanks

**Comment by filevans** [comment]
Also combo doesn't work properly for fuse, fuse has some weird GUI control behavior in general, so maybe a different core would be better. I will try to report them to the core developer, do you know if it has a github page? thanks

**Comment by SuperrSonic** [comment]
You don't have to turn on a wiimote, by default the reset button on the Wii is set to toggle the menu. If the user can remember to disable this then they can also remember to enable the menu combo setting.

It could be enabled alongside wiimotes, though it makes the code bigger, and since wiimotes have the home button, it really feels unnecessary.

It seems you've already found the github page.
