### ISSUE TITLE
Per game button configs

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#15]
Please could you add the ability to override the controller buttons per game, specifically for street fighter.2 games it is needed, thank you

**Comment by SuperrSonic** [comment]
Sorry, I'm not interested. This kind of work can take a lot of time, which I don't have much of.

However, you can use arguments to launch a specific game with a specific .cfg, but you need to make the core's .dol its own hbc app by renaming to boot.dol and adding a meta.xml with the arguments.

XML Example:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<app version="1">
  <name>Game Name</name>
  <version>1.0</version>
  <release_date>2019</release_date>
  <short_description>A short description.</short_description> 
  <long_description>A long description.</long_description> 
  <ahb_access/>
  <arguments>
    <arg>sd:/path/to/rom/</arg>
    <arg>rom name.zip</arg>
    <arg>sd:/path/and/name/of/config.cfg</arg>
  </arguments>
</app>

Version tags and release date can be removed. I'm not saying this is the superior way (I realize it's not.) but it is a good solution either way.

**Comment by filevans** [comment]
Thanks, when I've tried to use a cfg before with different button layout it messes up the menu navigation buttons and changes them too, is there any way to make it so it just affects the game buttons only and not GUI buttons? Thanks

**Comment by filevans** [comment]
It is possible override per game cfg on the normal version of retroarch so I don't see why it is so much work? Can't you just use the code from that? I've done it, it just messes up the navigation buttons along with it is the only problem

**Comment by SuperrSonic** [comment]
That won't happen here because the menu inputs are separated from core inputs.

It is true that porting it from official RA can help, but it's still time consuming and requires a lot of testing, I don't know how much memory it takes, which could break compatibility in some cores. If I change my mind I will let you know.

**Comment by filevans** [comment]
Having an extra cps1 and cps2 dol seems to be a good enough solution anyway, which section of the cfg should I edit please? I just want to change the right bit and not mess up the menu navigation buttons like it does in official retroArch

**Comment by SuperrSonic** [comment]
Fear of messing up the menu inputs is one of the reasons this exists. If you still mess up the menu, it simply means you're not using the latest version.

Like I said the menu inputs are separated from the core (the game itself.) There is no way to mess it up, unless you really want to change menu mappings.

**Comment by filevans** [comment]
I've done it now, I did it just for the 2 cores cps1 and cp2 not for every game, just for the 2 cores works well and then you can the handful of sf2 roms in each core. Having per game would be too much work and take up a lot of space and want needed. Thanks for your help, it works well

**Comment by SuperrSonic** [comment]
OK, disregard my previous replies, it's done. Test it if you can:
[cps2_per-game.zip](https://github.com/SuperrSonic/RA-SS/files/3338168/cps2_per-game.zip)

It will search for the game's .cfg in the 'config' path, if no .cfg is found nothing will be different.
To make a game specific .cfg you have to go to Settings->General, you will find two new settings:
-Create Per-Game Config
-Remove Per-Game Config

These are not really settings, but commands that will trigger when you press the 'accept' button. Don't worry about spamming the commands, it will only write to create the .cfg, if it exists it won't overwrite it.
Same goes for deleting, if there's no .cfg, it won't do anything.

There's one thing to note though, it doesn't work well if there's no 'core' specific .cfg being used, though you could just workaround that by providing .cfg files for every game.

One last detail, there is a RA-wide problem related to driver init/unint, after a certain amount of reloads it will hard crash. Usually around 16 reloads it crashes on dolphin so beware of loading too many games without a core reload. Hopefully I can find the cause, so I can bring back instant CPU filter switching.

**Comment by filevans** [comment]
Good work, will this only save buttons or will it be possible to save screen size too? I was thinking it would be good for cps1 and cps2 vertical games to be able to save different screen position/ resolution  etc

**Comment by SuperrSonic** [comment]
It's the full config.

**Comment by filevans** [comment]
You said if it exists it won't overwrite it so if you want to make a change later you can't overwrite it?

**Comment by SuperrSonic** [comment]
I meant the command to create the file won't trigger if the file exists, once it is loaded it is treated like a regular config, so saving rules are still the same.

**Comment by filevans** [comment]
Good work
