### ISSUE TITLE
Enable resolution switch to 50hz 288p

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#16]
Please could you add resolution switch to some 50hz 288p modes for PAL users, (352x288 something like that) and if you could also please add fuse core from official retroArch along with it? It would be really appreciated . Thank you

**Comment by SuperrSonic** [comment]
[fuse_test.zip](https://github.com/SuperrSonic/RA-SS/files/3342054/fuse_test.zip)

I'm not familiar with this core so test it and if it works I'll include it.

As for 50hz stuff, RA should already support this, does it not? No idea how it would be useful though, and 352 scales badly.

**Comment by filevans** [comment]
Yes it is needed for fuse to get native spectrum screen in pixel perfect ratio. 352x288 50hz is right, it does not scale badly that's a native pal resolution which 8bit pal computers use, like spectrum, c64, amstrad cpc

**Comment by filevans** [comment]
Please could you also include atari800? Which is in official RA

**Comment by SuperrSonic** [comment]
I'll include atari800 sure, but I am at a loss with the pal stuff, even if I force the existing pal code nothing happens in dolphin, which is the only tool I have.

**Comment by filevans** [comment]
I can test anything, could you do a version with a 50hz 288p mode on? Genplus gx for the Wii has built in 50/60 (288p/240p)  switch when you change region, if that helps, also nintendont can force PAL50/60

**Comment by SuperrSonic** [comment]
Just released an update, I left behavior mostly unchanged, if it detects a pal mode a new setting will show up in Settings->Video called "Force 288p" it will change (even if the labels don't) every 240p resolution to 288p 50Hz. This will override the system settings.

Luckily I was able to test with my current dolphin setup by removing every pal check, so after seeing it working I just put the checks back in.

**Comment by filevans** [comment]
Thanks a lot I'll test it tonight

**Comment by filevans** [comment]
Hello, I've just tested fuse and the force 288p works and pushed the console into PAL50 but the selectable resolutions only have 224p and 240p modes and no 288p. 

Also on fuse when you press select to get the virtual keyboard and while in the keyboard the button pressing is spasmodic like it's pressing everything twice or something like that.

Also in fuse core options on official RA there should be joystick type setting: kempston, Sinclair, cursor etc. needed to control games but on this version it's missing and doesn't seem to be carrying over the universal joystick mappings either.

Thanks

**Comment by SuperrSonic** [comment]
The labels won't change, they are taken directly from the list.

When force 288p is enabled and a double-strike res is used, the total amount of lines is changed to 288.

This means that 640x240p, 352x240p, 608x224p, etc. will become the same as 288p. If you had menu bilinear off, it would show all distorted meaning that it is working.

I don't know anything about the fuse core, but they're always changing the libretro api so backwards comp is sometimes a problem. If this core worked at some point pre-1.0.0.3 then it might be better to use that version.

**Comment by filevans** [comment]
No, the latest official fuse core has these options in, but the one you've added doesn't,  has joystick type missing and entering and navigating virtual keyboard is erratic, it isn't like that on the latest official RA fuse core. 

If I use the official one then it won't work with your tweaks will it? So won't it defeat the purpose of requesting 288 if I do that?

**Comment by SuperrSonic** [comment]
I'm giving fuse a go now, when you say joystick type you mean 'Device  Type' under RA? It lists seven types here which matches the source: https://github.com/libretro/fuse-libretro/blob/master/src/libretro.c#L500

I tried Advanced Pinball Sim, using Kempston Joystick though I had to configure the inputs using the core options. The repeated keyboard commands only happened on GC controllers but once I got to the gameplay it started working fine, I don't get it, the cores without vsync, handy, wswan, and pokemini had this issue but was fixed by changing the polling rate to 1, this is the global default and since fuse is using 50 fps if audio sync is enabled then vsync is also not in effect. Maybe it has to do with this https://github.com/libretro/fuse-libretro/blob/master/src/libretro.c#L954

On the bright side I found that this game at least runs at a steady 130 fps with normal2x enabled, so you can get a sharper image than 352, which is considerably soft on GC/Wii.

**Comment by filevans** [comment]
Sorry for the delay replying, yes I can send you a screen grab of the official RA fuse it has  the kempston joystick options and the virtual keyboard doesn't access and move spasmodically (repeat presses) yes the emulation speed is good but seems like there's some interface bugs compared to official RA fuse

**Comment by Kingharthacnut** [comment]
> Sorry for the delay replying, yes sorry, kempston joystick type must be in a different place as I couldn't find it. the virtual keyboard access and moves spasmodically (repeat presses) yes the emulation speed is good but seems like there's some interface bugs compared to official RA fuse (maybe core update introduced some bugs). Could you please fix the repeat key press problem? Maybe use slightly older core? On official RA fuse the joystick mappings are carried over from global but on the core you sent me it didn't, they were all blank
> 
> A side topic, is there vice, uae or Atari ST cores available per chance?

After Sir Clive passed away last week I've been hankering for a bit of Spectrum action a 14" CRT. 

Did the 50hz thing workout filevans? I really want to get the full late 80s effect on my little TV via a Wii.
