### ISSUE TITLE
Cfg can get mixed up when launching RA from a core instead of boot.dol

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#18]
Hello, I've had Cfg get mixed up when launching RA from a core instead of boot.dol, you know if you launch from usb loader gx's internal homebrew launcher it shows all RA dols and you don't know which is the boot.dol, well a couple of times say I've exited out from RA from nestopia core then the next time, launched beetle pce fast core from usb loader gx homebrew launcher, the settings came up as my saved cfg from nestopia, with same resolution / video settings and specified nes Rom folder instead of loading my previous saved pce fast cfg settings . Has happened a few times with different cores and I've had to change everything back again

**Comment by filevans** [comment]
This still happens on the new release and happens even when launching boot dol, sometimes it retains rom folder and screen settings from previous session core, and cfg spills over into new session/ different core

**Comment by SuperrSonic** [comment]
Since the goal of the Hexaeco release is to offer a fallback for when RA-Wii fails and to better support "single game runs," I'm going to skip on this.
