### ISSUE TITLE
Gambatte Core Palette options seemingly don't work anymore.

### ISSUE THREAD

**Issue by Maesejesus** [SuperrSonic/RA-SS#19]
I've noticed this since a month or so, and I waited for an update, and just tried the one from July 6th, but it still happens.

In older versions, you could change the Palette used for original Game Boy games, and it was a very simple and direct process. You went to Core Options, selected the Palette you wanted, and exited the GUI to go back to the game, now with the new palette. The game didn't even reset or anything, which was great.

Now, it seems like the emulator is forced into using a specific palette (one where green\blue is for background graphics and red is used for moving sprites). I tried changing every option in Core Options, yet it didn't change anything.

Maybe I'm doing something wrong, but previously it worked like a charm, so I'm somewhat inclined to think it has some sort of issue.

Keep the good work, SuperrSonic!

**Comment by SuperrSonic** [comment]
To use internal palettes set the core option "GB Colorization" to -internal- and then "Internal Palette" to select the palette like you did before.

I know you said you tried every core setting, but this is the only relevant one. Is this not working?

**Comment by Maesejesus** [comment]
I really can't explain why, but after trying for a while again, I decided to delete the .cgf file. After configuring the Gambatte core again, now works just as you say. I don't get it, but I suppose that it was a problem on my end.

Sorry for bothering you, SuperrSonic.
