### ISSUE TITLE
"snes9x.dol" error "Save Data" and "Save State Data"

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#20]
SuperrSonic estava testando o núcleo "snes9x.dol" mais especificamente em jogos MSU-1 e percebi que quando vai gravar o progresso utilizando o "Save Data" ou o "Save State Data" trava o núcleo, depois testei em jogos de Super Nintendo e constatei que ocorre o mesmo problema.

Na versão 1.7.6 oficial esta perfeito o núcleo "snes9x.dol", nas versões mais novas não testei!

**Comment by SuperrSonic** [comment]
Should be good now. I just never updated the core ever since msu-1 support was added. Also I've re-added the cps-3 core with Wiimpathy's changes.

**Comment by rogerioronin** [comment]
Obrigado pela atualização, esta tudo funcionando corretamente no núcleo "Snes9x.dol"!

O núcleo "CPS-3" modificado pelo Wiimpathy quando testei achei de pouca utilidade, porque a maior parte dos jogos funcionam lento, mas vou testar novamente!

Obrigado pelo ótimo trabalho!

**Comment by filevans** [comment]
I use snes 9x gx as RA snes 9x core runs games slower for some reason
