### ISSUE TITLE
vm_fba2012_neogeo.dol "Screen Resolution configuration files"

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#22]
A sua versão do core "vm_fba2012_neogeo.dol" suporta os arquivos disponibilizados aqui "https://gbatemp.net/threads/retroarch-arcade-sort-games-and-screen-resolution-configuration-files.538198/" ?

**Comment by SuperrSonic** [comment]
La opción de usar 'overrides' esta disponible aqui, pero el setting de resolución tiene otro nombre y una cantidad diferente.
