### ISSUE TITLE
Neogeo large rom support

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#23]
Please would it be possible to add large rom support (for some of the larger KOF games) someone seems to have made this modification here by using virtual memory:

https://gbatemp.net/threads/large-neogeo-games-support-and-cps3-tests.493767/

Thanks a lot

**Comment by SuperrSonic** [comment]
It's already available, "vm_fba2012_neogeo"

**Comment by filevans** [comment]
Sorry didn't see that. My apologies
