### ISSUE TITLE
 sound error in CHD games on Nintendo Wii

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#24]
Jogos de PC Engine CD em CHD funcionam bem nos núcleos do Retroarch, mas o som (audio) por algum motivo esta com problema, não teria como você resolver este problema?

Obrigado pelo belo trabalho!

**Comment by rogerioronin** [comment]
Realmente eu uso formato "ISO+OGG" e funciona bem, mas seria interessante funcionar os jogos no formato CHD.

Mas este é um problema sem muita importância!

A versão do Genplus esta atualizada ?

**Comment by filevans** [comment]
I think you should use Gen Plus GX standalone emulator as it is excellent

**Comment by rogerioronin** [comment]
sim a versão GX é excelente, mas a versão retroarch aceita filtro de vídeo!

**Comment by saulfabregwiivc** [comment]
I have same issue with CHD games of PC Engine CD / TurboGrafx-CD on RetroArch Wii RA-HEXAECO (specifically the core beetle_pce_fast.dol). They load and are playable but they have sound/audio problems.

Any way for fix this?

**Comment by SuperrSonic** [comment]
No more core support.
