### ISSUE TITLE
Change difficulty dipswitches in CPS1

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#25]
Hello,
Please is it possible to change difficulty in street fighter 2 games in FBA CPS1, yes it's possible to enter diagnostic in CPS2 and do it but in CPS1 the difficulty isn't in the diagnostic menu but it's done in the separate dipswitch menu in MAME main menu and FBA (in Windows emulators)

**Comment by SuperrSonic** [comment]
No more core support.
