### ISSUE TITLE
Atari 800 error

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#27]
Eu tentei usar este núcleo, usando as BIOS especificas, mas não consegui, tem certeza que este núcleo esta funcionando corretamente ?

**Comment by SuperrSonic** [comment]
I can't confirm if it works. Does it work in official RA Wii?

**Comment by rogerioronin** [comment]
> I can't confirm if it works. Does it work in official RA Wii?

Na versão oficial não funciona, ao menos todos os testes que fiz não consegui iniciar jogos!

**Comment by metallic77** [comment]
It doesn't start on my Wii too, and not in official retroarch too. Just a black screen.

**Comment by SuperrSonic** [comment]
No longer interested.
