### ISSUE TITLE
Button combo set to default

### ISSUE THREAD

**Issue by filevans** [SuperrSonic/RA-SS#29]
Hello, please could you make some changes to the exit button combo? Firstly please still allow it, even if the Wiimote is on, as sometimes I have my remote on, for just turning console on and off, but I'm not using it, and if it's on, the GameCube controller exit button combo won't work

Also could it be enabled to 1 by default? As it is a lot of hassle scrolling all the way down input options to find and change it on every single core, and if you forget to do it when changing core it means you have to get up to press reset on the Wii to get back to the menu

And finally could you put the option at the top of the input menu instead of a long way down as it makes it more hassle to enable it every time when it's so far down, and unlike the ROM browser menu you can't use left/right to page down inside the options menu

Thank you

**Comment by SuperrSonic** [comment]
It's unfortunate that this is an inconvenience but I'm not interested in this part of RA anymore. Making the button combo the default is ugly when you have better ways available (right stick, HOME button, reset button.) Moving the option up is the easiest to do of course but is it really necessary? The option is set once if you need it, there's no reason to keep changing it.

**Comment by filevans** [comment]
No it's not enabled once, you have to remember to change it for EVERY core, it's miles down the list and awkward to find and change on every core, and if you forget then you can't get out of the menu, and if you're Wiimote isn't on you can't use it as it won't sync afterwards, has to be synced on startup, and if you activate the Wiimote to do it then the button combo won't work on the controller as they don't work simultaneously, so it's a hassle

Button combo should work simultaneously with other exit options and be easier and quicker to activate not trawling through a long list to find it on every single core. I mean at least make it so you can set it on for all cores and not have to do it every time you load a new core?? Someone could be using 20 cores and you have the hassle of finding it in the menu for 20 cores!

**Comment by filevans** [comment]
If you start RA with your wiimote on then it ignores the exit to menu controller button combo, regardless of whether you have combo set to 1 or not. Can you at least resolve that? If I set menu key combo to 1 it should work on the controller even if I have the Wiimote on so I don't have to keep reaching for the wiimote, everything should be controllable from the controller/ joystick you're using without having to switch between them

**Comment by SuperrSonic** [comment]
OK, the wiimote should no longer cause a conflict.
