### ISSUE TITLE
SNES9x 2002

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#3]
SuperrSonic the official version of Snes9x2002 does not work, is it possible for you to provide the core compiled in this version 1.0.0.2-SS that works?

**Comment by SuperrSonic** [comment]
Latest snes9x2002 doesn't compile for old retroarch versions. I'd have to remove some stuff, but I remember trying a long time ago and loading any game would exit.

Do you remember this core ever working on Wii? It seems to be like the other arm optimized cores, they just won't run on Wii.

**Comment by rogerioronin** [comment]
Really the core Snes9x2002 never worked on the Nintendo Wii!
