### ISSUE TITLE
Issue with Classic Controller Analog Stick in GenPlus GX Core

### ISSUE THREAD

**Issue by Maesejesus** [SuperrSonic/RA-SS#31]
Hi SuperrSonic, I hope you see this!
I wanted to inform that Analog stick inputs for left and right directions (or diagonal directions for that matter) for some reason don't work, while on other cores they do. I tried with a completely new install, from 3th July.

I do not know how long has this issue been existing, I just found out recently.

I wish you're doing okay!

**Comment by SuperrSonic** [comment]
It works in dolphin, that's all I can test since I only have GC controllers.

Could you check if they work in the gui? Also check if Input->User 1 Left analog X is mapped.

**Comment by Maesejesus** [comment]
Thank you for your response!
I've been messing with the settings and for some reason after rebinding the inputs it worked fine again. But it's weird because it only happened with the GenPlus GX core (or "cores" as I have a couple of copies with different set ups different for each) and my Classic Controllers are original, not third party.

In any case it was an issue on my end, and not with your work. Sorry for bothering you!
