### ISSUE TITLE
Support for USB Hid controls in RA-SS

### ISSUE THREAD

**Issue by spielvan** [SuperrSonic/RA-SS#34]
Hello my friend @SuperrSonic ,  a friend would like to know if the RA-SS has support for USB controls by the HID system, if not, do you intend to add it in the future? a big hug

**Comment by SuperrSonic** [comment]
Currently it doesn't. It's difficult to work on the controller part of RA because it's really confusing to me and messy, I would like to do it but it's something that could take a long time to get it working correctly, so I don't know when.

**Comment by SuperrSonic** [comment]
I'm no longer interested in this feature.
