### ISSUE TITLE
Slowdown in some SEGA 32X games in PicoDrive core of RA-HEXAECO

### ISSUE THREAD

**Issue by saulfabregwiivc** [SuperrSonic/RA-SS#35]
Hello @SuperrSonic 

I am saulfabreg, SaulFabre in GBAtemp (@saulfabregwiivc in GitHub)

I have a issue to report: in the core of PicoDrive Wii (picodrive.dol) of your version v11-07-2021 of RA-HEXAECO, the emulated SEGA 32X / Mega Drive 32X in Wii are going slow.

I tried with Knuckles' Chaotix with that core, it loads and it can be played, but it can't be enjoyed because of the slowdown. I tried with libretro's newest nightly version of RetroArch Wii (24-07-2021) where that slowdown isn't present but it lacks all the interesting features of your RA-HEXAECO version.

Can you fix the PicoDrive Wii RA-HEXAECO core for a next version?

Thanks @SuperrSonic for your great work with RetroArch Wii, i'm so glad to have a great multi-emulator for Wii :)

**Comment by SuperrSonic** [comment]
If you're really thankful don't bundle my builds with ROMs. What you're doing is wrong and is a massive disrespect to the work of numerous developers. I know I can't stop you but you don't seem like a bad person, so please reconsider.
