### ISSUE TITLE
Applying a small improvement on mGBA Wii core of RA-HEXAECO for improve speed?

### ISSUE THREAD

**Issue by saulfabregwiivc** [SuperrSonic/RA-SS#36]
Hi @SuperrSonic 

Nice work again with your RA-SS / RA-HEXAECO work, which for me is the best RetroArch Wii i've used.

The speed of mGBA Wii is fine, but i wanted to apply a small modification on your repository https://github.com/SuperrSonic/mgba/ for improve the speed and stability of the emulation by decreasing audio buffer samples, and hope also this can be applied to the RA-HEXAECO version of mGBA Wii too.

See pull request https://github.com/SuperrSonic/mgba/pull/1 for more info about this.

Hope this will be applied in a next version of RA-HEXAECO, and don't forget about the new updates of the cores of Libretro RetroArch Wii, with your changes and fixes.

Greetings ;)

**Comment by SuperrSonic** [comment]
This wouldn't have any effect because the core I used is from last year, which already does what you want.
