### ISSUE TITLE
PicoDrive core SRAM broken

### ISSUE THREAD

**Issue by gingerbeardman** [SuperrSonic/RA-SS#37]
This is a problem I previously reported to mainline libretro/picodrive, here: https://github.com/libretro/picodrive/issues/153

Game used to test: [Pebble Beach Golf Links](https://segaretro.org/Pebble_Beach_Golf_Links_(Mega_Drive))

The symptoms are many:
- edited player names are not saved
- menu refuses to proceed to gameplay
- game progress is not saved
- after hole 9 game goes crazy ([ref](https://github.com/notaz/picodrive/issues/66))

It's been broken [more than once](https://github.com/notaz/picodrive/issues/64) but was most recently fixed on 29 May 2021:
https://github.com/libretro/picodrive/commit/78c2237ab8cf410b7cb1f4875acd419acd8a9da3 which made it into 1.9.4, if my understanding of the dates is correct.

Hopefully that fix can be integrated in RA-SS?

**Comment by saulfabregwiivc** [comment]
Same issue with PicoDrive core here.
And still some slowdown in RA-HEXAECO PicoDrive core... (in the 2021-07-11 version)

**Comment by SuperrSonic** [comment]
No longer providing core updates.
