### ISSUE TITLE
PokeMini core (and Handy & WonderSwan cores) won't save or load savestates, and some crashes still ocurrs :(

### ISSUE THREAD

**Issue by saulfabregwiivc** [SuperrSonic/RA-SS#40]
Hi @SuperrSonic

I saw you released a new version of RA-HEXAECO on r05-11-2021, but PokeMini core (and maybe other no vsync cores Mednafen WonderSwan and Handy Atari Lynx) now won't save nor load savestates... :(

Any help please? Can you fix it so we can enjoy also to use savestates? Or this will crash again those cores?

EDIT: My friend RunningSnakes also experienced these issues: he tried Pokemini, WonderSwan, Handy and all boot games fine. The problem is all will crash after playing 10-15 seconds into play and also running at 76-78 FPS. Going back to previous versions, he is experiencing no issues. They are known problem cores obviously since you (SuperrSonic) keep twerking these. (??)

Can you fix those problems please?
Please sorry me if i bother you again.

Thanks, @saulfabregwiivc

**Comment by tesla0306** [comment]
gba gives me problems when doing load state
gba me da problemas al hacer load state
