### ISSUE TITLE
Fix compatibility with new v1.1 version of romhack "Super Mario Bros. 1/3"?

### ISSUE THREAD

**Issue by saulfabregwiivc** [SuperrSonic/RA-SS#42]
On this modification of FCEUmm (FCEUmm-Mod) for support the advanced romhack made by Corpse Grinder "Super Mario Bros. 1/3" (https://github.com/Tippek/libretro-fceumm-mod) it was updated on December 23, 2021 for make it compatible for the new v1.1 version of this romhack, released on December 4, 2021.

Unfortunately the fceumm-mod_SMB1-3.dol of the most recent RA-HEXAeco (May 7, 2022) doesn't support the new 1.1 version, only the 1.0. And that's a shame because 1.1 fixes a lot of bigs that were present on 1.0:

Super Mario Bros. 1/3 (v1.1)
=
- fixed many bugs
- added 2 bosses
- fixed some music
- chars gfx from snes smb3

Could you add the updated code from libretro-fceumm-mod to that core for a next release? Thanks!!
PD: I will leave their SMB 1/3 Discord server for check it out: https://discord.gg/qV7Db9m

EDIT: I've explained this a little more here: https://gbatemp.net/threads/the-great-quest-for-wiiflow-plugins-tm-a-call-for-adventurers.563575/post-9834089

**Comment by SuperrSonic** [comment]
No longer providing core updates.
