### ISSUE TITLE
Won't start until I start and quit a working program. 

### ISSUE THREAD

**Issue by Kingharthacnut** [SuperrSonic/RA-SS#44]
RA-SS won't load unless I load a program that works and quit it first. (I've been using FBZX Wii)

I've tried on running from USB and SD with the same result.

RA-SS also won't load up when my USB keyboard is plugged in. (I've tried an HP and Microsoft Keyboard). Again, I get the same result whether I run it from SD or USB. (Both keyboards work on FBZX Wii)

Could my IOSes be out of date?

**Comment by SuperrSonic** [comment]
You could try loading one of the cores as a standalone app and see if it becomes stable.

Does it return you to hbc? Or does it get stuck in a black screen. If it's stuck in a black screen, does pressing the power button return you to hbc?

Does the keyboard crash happen in official RA? As long as you have an unmodified IOS 58 and a decent way to load the app, I see no link to the system files.

**Comment by Kingharthacnut** [comment]
It's seems Retroarch Wii doesn't initialize USB Keyboards. 

I've checked Official Release, RA-SS and a standalone Fuse core.

**Comment by SuperrSonic** [comment]
No longer providing core updates.
