### ISSUE TITLE
PicoDrive core crashes when loading a game

### ISSUE THREAD

**Issue by SheepyChris** [SuperrSonic/RA-SS#45]
Issue is self explanatory, when attempting to load a 32X game with PicoDrive it'll crash the system back to the Homebrew Channel, latest RA-SS version (Sep 9, 2022) used. Tested with Virtua Racing Deluxe and Doom, if there are any other useful logs that I can provide let me know.

**Comment by SuperrSonic** [comment]
This can be solved by updating the core. But I am no longer providing core updates.
