### ISSUE TITLE
Handy

### ISSUE THREAD

**Issue by rogerioronin** [SuperrSonic/RA-SS#5]
Hi superrSonic, is it possible to compile the Handy ?

https://github.com/libretro/libretro-handy

**Comment by SuperrSonic** [comment]
Done.

**Comment by rogerioronin** [comment]
I tested here and this nucleus is not working.

Thanks for this great work!

**Comment by SuperrSonic** [comment]
I tested it now and got Ms. Pac-Man to start. Could you try more games maybe?

**Comment by rogerioronin** [comment]
Really SuperrSonic this core is working perfectly, sorry for my mistake!
